function [ info_array ] = makeChannelInfoStruct(  )
%MAKECHANNELINFOSTRUCT Summary of this function goes here
%   Detailed explanation goes here

ControllerSN = num2cell(zeros(256,1, 'uint16'));
firmware = num2cell(zeros(256,1, 'uint16'));
DeviceSN = num2cell(zeros(256,1, 'uint16'));
position = num2cell(zeros(256,1, 'uint32'));
index = num2cell(zeros(256,1, 'uint32'));
indexID = num2cell(zeros(256,1, 'uint32'));
InstrType = num2cell(zeros(256,1, 'uint32'));

info_array = struct(...
    'ControllerSN', ControllerSN,...
    'firmware', firmware,...
    'DeviceSN', DeviceSN,...
    'position', position,...
    'index', index,...
    'indexID', indexID,...
    'InstrType', InstrType);
end

